import { registerEnumType } from 'type-graphql'

export enum EAuditActions {
  // Authentication
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',

  // User Management
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE',
  APPROVE_USER = 'APPROVE_USER',
  DENY_USER = 'DENY_USER',
  UPGRADE_ACCOUNT_REQUEST = 'UPGRADE_ACCOUNT_REQUEST',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  VERIFY_PHONE_NUMBER = 'VERIFY_PHONE_NUMBER',
  UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN',
  REMOVE_FCM_TOKEN = 'REMOVE_FCM_TOKEN',

  // Driver Management
  REGISTER_DRIVER = 'REGISTER_DRIVER',
  UPDATE_DRIVER_DETAIL = 'UPDATE_DRIVER_DETAIL',
  CHANGE_DRIVING_STATUS = 'CHANGE_DRIVING_STATUS',
  ADD_EMPLOYEE = 'ADD_EMPLOYEE',
  ACCEPT_EMPLOYEE_REQUEST = 'ACCEPT_EMPLOYEE_REQUEST',
  REJECT_EMPLOYEE_REQUEST = 'REJECT_EMPLOYEE_REQUEST',
  REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE',

  // Shipment/Booking Management
  CREATE_SHIPMENT = 'CREATE_SHIPMENT',
  UPDATE_SHIPMENT = 'UPDATE_SHIPMENT',
  ACCEPT_SHIPMENT = 'ACCEPT_SHIPMENT',
  REJECT_SHIPMENT = 'REJECT_SHIPMENT',
  CANCEL_SHIPMENT_CUSTOMER = 'CANCEL_SHIPMENT_CUSTOMER',
  CANCEL_SHIPMENT_DRIVER = 'CANCEL_SHIPMENT_DRIVER',
  CANCEL_SHIPMENT_SYSTEM = 'CANCEL_SHIPMENT_SYSTEM',
  CONTINUE_MATCHING = 'CONTINUE_MATCHING',
  CONFIRM_SHIPMENT_DATETIME = 'CONFIRM_SHIPMENT_DATETIME',
  NEXT_SHIPMENT_STEP = 'NEXT_SHIPMENT_STEP',
  SENT_POD_DOCUMENT = 'SENT_POD_DOCUMENT',
  FINISH_SHIPMENT_JOB = 'FINISH_SHIPMENT_JOB',
  ASSIGN_SHIPMENT_DRIVER = 'ASSIGN_SHIPMENT_DRIVER',

  // Financial Management
  CREATE_BILLING = 'CREATE_BILLING', // This might be a system action mostly
  UPDATE_BILLING = 'UPDATE_BILLING',
  APPROVE_BILLING_PAYMENT = 'APPROVE_BILLING_PAYMENT',
  REJECT_BILLING_PAYMENT = 'REJECT_BILLING_PAYMENT',
  REFUND_BILLING_PAYMENT = 'REFUND_BILLING_PAYMENT',
  CONFIRM_WHT_DOCUMENT_RECEIVED = 'CONFIRM_WHT_DOCUMENT_RECEIVED',
  MAKE_ADDITIONAL_PAYMENT = 'MAKE_ADDITIONAL_PAYMENT',
  CREATE_DRIVER_PAYMENT = 'CREATE_DRIVER_PAYMENT',

  // Settings Management
  UPDATE_CONTACT_US = 'UPDATE_CONTACT_US',
  UPDATE_ABOUT_US = 'UPDATE_ABOUT_US',
  UPDATE_CUSTOMER_POLICIES = 'UPDATE_CUSTOMER_POLICIES',
  UPDATE_CUSTOMER_TERMS = 'UPDATE_CUSTOMER_TERMS',
  UPDATE_DRIVER_POLICIES = 'UPDATE_DRIVER_POLICIES',
  UPDATE_DRIVER_TERMS = 'UPDATE_DRIVER_TERMS',
  UPDATE_BUSINESS_TYPE = 'UPDATE_BUSINESS_TYPE',
  UPDATE_FAQ = 'UPDATE_FAQ',
  UPDATE_INSTRUCTION = 'UPDATE_INSTRUCTION',
  UPDATE_FINANCIAL_SETTING = 'UPDATE_FINANCIAL_SETTING',

  // Pricing Management
  ADD_ADDITIONAL_SERVICE_COST = 'ADD_ADDITIONAL_SERVICE_COST',
  UPDATE_ADDITIONAL_SERVICE_COST = 'UPDATE_ADDITIONAL_SERVICE_COST',
  UPDATE_DISTANCE_COST = 'UPDATE_DISTANCE_COST',
  INITIAL_VEHICLE_COST = 'INITIAL_VEHICLE_COST',
  INITIAL_ADDITIONAL_SERVICE_COST = 'INITIAL_ADDITIONAL_SERVICE_COST',

  // Other
  UPLOAD_FILE = 'UPLOAD_FILE',
  CREATE_CONTACT_MESSAGE = 'CREATE_CONTACT_MESSAGE',
  ADD_FAVORITE_DRIVER = 'ADD_FAVORITE_DRIVER',
  REMOVE_FAVORITE_DRIVER = 'REMOVE_FAVORITE_DRIVER',
  ADD_POD_ADDRESS = 'ADD_POD_ADDRESS',
  REMOVE_POD_ADDRESS = 'REMOVE_POD_ADDRESS',
  SAVE_EVENT = 'SAVE_EVENT',
  REMOVE_EVENT = 'REMOVE_EVENT',
  ACCEPT_POLICY = 'ACCEPT_POLICY',
}

registerEnumType(EAuditActions, {
  name: 'EAuditActions',
  description: 'Actions performed by users for auditing purposes',
})