export const REPONSE_NAME = {
  NOT_FOUND: "NOT_FOUND",
  EXISTING_SHIPMENT_DRIVER: "EXISTING_SHIPMENT_DRIVER",
  SEARCH_LIMIT: 'SEARCH_LIMIT',
  SEARCH_BANNED: 'SEARCH_BANNED',
  SHIPMENT_NOT_FINISH: 'SHIPMENT_NOT_FINISH',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
}