type TShipingStatus = 'PENDING' | 'ACCEPTED' | 'DELIVERED' | 'CANCELLED'
type TIssueType = 'DELAY' | 'DAMAGE' | 'MISSING' | 'OTHER'
type TPaymentStatus = 'WAITING_FOR_WORK_COMPLETE' | 'WAITING_FOR_PAYMENT' | 'PAID' | 'CANCELLED'